name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Todo API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/ToDoService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:latest
      -
        name: Build and push Admin API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/AdminService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/admin-api:latest

      -
        name: Build and push Todo UI
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/TodoUI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-ui:latest
