name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Move to Admin Repo
      run: cd src/AdminService
    - name: Build the Docker image
      run: docker build . --tag todo/admin-api:$(date +%s)
